### ISSUE TITLE
Possible typo in the paper

### ISSUE THREAD

**Issue by OmPrasad93** [rungjoo/CoMPM#1]
The paper explains the CoMPM figure in Page 4 and states:
_Figure 2: Our model consists of two modules: a context embedding module and a pre-trained memory module.
The figure shows an example of predicting emotion of u 6 , from a 6-turn dialogue context. A, B, and C refer to the
participants in the conversation, where s A = p u 1 = p u 3 = p u 6 , s B = p u 2 = p u 5 , s C = p u 3 . W o and W p are
linear matrices._
I believe s C = p u 3 should be s C = p u 4

**Comment by rungjoo** [comment]
Your opinion is correct. Thanks for pointing it out.
