### ISSUE TITLE
Can I use this work for sentiment analysis of dyadic conversations?

### ISSUE THREAD

**Issue by anuragrawal2024** [rungjoo/CoMPM#11]
Hi,

I am working on sentiment analysis of dyadic conversations. Can I use your work for this purpose?

I understand that this work can help with utterance-level sentiment/emotion recognition in conversations? Now from there, if I want to recognize sentiment/emotion of the whole conversation, are you aware of any techniques that might help?

Thank you so much for your help!

**Comment by rungjoo** [comment]
Sorry for my belated reply.

Our method can be used for emotion recognition of utterances in conversations.
In other words, both one-on-one conversations and multi-chat conversations are available.

Does emotional recognition for the whole conversation refer to the session?
If so, the dataset below may be helpful.
Look for references on this!
ScenarioSA: A Dyadic Conversational Database for Interactive Sentiment Analysis, IEEE Access 2020
