### ISSUE TITLE
pytorch-cuda version for the source code?

### ISSUE THREAD

**Issue by anuragrawal2024** [rungjoo/CoMPM#12]
Hi,

Do you know which version of cuda the code was built using? Prerequisites listed pytorch 1.8 but didn't say with which version of cuda. I am finding it very difficult to run because I couldn't find torch 1.8 anywhere. Appreciate your help!

**Comment by anuragrawal2024** [comment]
Never mind! The code works as-is with pytorch '2.0.1+cu117'

**Comment by rungjoo** [comment]
Thanks!
