### ISSUE TITLE
Google Drive link not found

### ISSUE THREAD

**Issue by goonbamm** [rungjoo/CoMPM#3]
I clicked the link, but the message is like below.

"404. 오류가 발생했습니다. 요청하신 URL을 서버에서 찾을 수 없습니다. 다른 원인은 확인할 수 없습니다."

Could you fix this problem?

**Comment by rungjoo** [comment]
구글드라이브에서 파일을 내려서 링크가 잘못된 오류네요.
다시 구글드라이브에 올려서 다시 링크를 걸어두겠습니다.

걸어두고 다시 메일보내드릴게요.
감사합니다.
이주성 드림.

2022년 11월 17일 (목) 오전 10:35, Jiyeol Park ***@***.***>님이 작성:

**Comment by goonbamm** [comment]
이렇게 빠르게 받아주셔서 진심으로 감사드립니다. 논문 정말 잘 읽었습니다. 좋은 하루 되세요 :)

**Comment by rungjoo** [comment]
관심 가져주셔서 감사합니다~!
모델링크가 수정되어서 다운로드 가능할거에요.
