### ISSUE TITLE
"MELD_models/roberta-large/pretrained/no_freeze/emotion/1.0/model.bin" . It doesn't have mobel.bin file.

### ISSUE THREAD

**Issue by Aidenfaustine** [rungjoo/CoMPM#5]
sorry to disturb you. I have trouble about "CoMPM: Context Modeling with Speaker’s Pre-trained Memory Tracking for Emotion Recognition in Conversation".

when  I run the command "python train.py".

it is reported the issue as follows: "MELD_models/roberta-large/pretrained/no_freeze/emotion/1.0/model.bin" . It doesn't have mobel.bin file.

could you please help me to solve it?  I want to reproduce your work based on your code. 
many thanks 
best wishes

![435f842d4ae6069c562c230eaad8d38](https://user-images.githubusercontent.com/82608348/226168506-b9f64667-fab0-4a4f-9daa-0b626b35891c.png)

**Comment by rungjoo** [comment]
Looking at the attached code, it seems that test.py was executed.
A trained model is required to run test.py, which can be downloaded from [drive](http://naver.me/FFi8Y74W).

**Comment by Aidenfaustine** [comment]
many thanks for your help.
