### ISSUE TITLE
reproduce your work on MELD dataset, the weight F1 score is 66.52

### ISSUE THREAD

**Issue by Aidenfaustine** [rungjoo/CoMPM#6]
your work is interesting and perfect. don't introduce external knowledge, just dependent on CoM and PM. 

when i try to reproduce same result in MELD dataset. I want to achieve same result F1 score is 66.52.

use the command :python test.py? it is right? do need to setup other experiments.

could you please give me a hand? many thanks 

![image](https://user-images.githubusercontent.com/82608348/226385164-fe10c65c-59fe-4526-bad4-0fb46a78119f.png)

![image](https://user-images.githubusercontent.com/82608348/226386214-83725f4f-ff85-4c5a-9c22-57f1bb847b96.png)

**Comment by rungjoo** [comment]
Yes, that's right.
First, you need to learn the model for specific data through train.py. (rr download the model from drive.)

Next, you can evaluate the model through test.py.
test.py is a file written assuming when there is a model for all four datasets.
If you want to evaluate a model for one dataset, modify the code with specific data with https://github.com/rungjoo/compm/blob/master/test.py#l41.

Ex) Test for MELD
```
dataset_list = ['MELD']
DATA_loader_list = [MELD_loader]
```

**Comment by Aidenfaustine** [comment]
Thank you for your details advice, great work
