### ISSUE TITLE
UnboundLocalError: local variable 'DATA_loader' referenced before assignment

### ISSUE THREAD

**Issue by Aidenfaustine** [rungjoo/CoMPM#8]
when i run the command "python train.py  --initial {pretrained} --cls {emotion} --dataset {MELD}" .

it is reported the error as follows: "UnboundLocalError: local variable 'DATA_loader' referenced before assignment " .

how to fix it ？ 
many thanks

**Comment by rungjoo** [comment]
Sorry for late.

link: [dataset ](https://github.com/rungjoo/CoMPM/blob/master/train.py#L43)
The type of dataset should be assigned.
If you enter anything other than the 4 datasets, you will get an error.

Try:
`python train.py --initial pretrained --cls emotion --dataset MELD`
Don't use {}
